### ISSUE TITLE
can not compile use `make`

### ISSUE THREAD

**Issue by mclyk** [Zondax/ledger-parallel#4]
Hello, when I am trying to compile use `make`, an error happens, do you know the reason, Why cargo can not be used in a docker container, and how to fix this?

```
docker run "-t" "-i" --rm -e SCP_PRIVKEY=ff701d781f43ce106f72dc26a46b6a83e053b5d07bb3d4ceab79c91ca822a66b -e BOLOS_SDK=/project/deps/nanos-secure-sdk -e BOLOS_ENV=/opt/bolos -u 0 -v /root/ledger-parallel:/project -e SUPPORT_SR25519= -e SUBSTRATE_PARSER_FULL=1 -e COIN= -e APP_TESTING= zondax/builder-bolos:latest "make -C /project clean"

--------------------------------------
Zondax BOLOS container - zondax.ch
--------------------------------------

/tmp/entrypoint.sh: line 10: /root/.cargo/env: No such file or directory
BOLOS_ENV=/opt/bolos BOLOS_SDK=/project/deps/nanos-secure-sdk

make: Entering directory '/project'
"Calling app Makefile for target clean"
COIN= make -C app clean
make[1]: Entering directory '/project/app'
TARGET_NAME=TARGET_NANOS TARGET_ID=0x31100004 TARGET_VERSION=2.1.0
BOLOS_ENV=/opt/bolos
************ TARGET_NAME  = [TARGET_NANOS]
************ FULL PARSER ENABLED ************
COIN  = [PARA]
TARGET_NAME  = [TARGET_NANOS]
ICONNAME  = [/project/app/nanos_icon.gif]
BOLOS_ENV is /opt/bolos
cd rust && CARGO_HOME="/project/app/rust/.cargo" cargo clean
/bin/bash: cargo: command not found
make[1]: *** [Makefile:234: rust_clean] Error 127
make[1]: Leaving directory '/project/app'
make: *** [Makefile:36: clean] Error 2
make: Leaving directory '/project'
make[1]: *** [/root/ledger-parallel/deps/ledger-zxlib/dockerized_build.mk:146: clean_build] Error 2
make[1]: Leaving directory '/root/ledger-parallel'
make: *** [/root/ledger-parallel/deps/ledger-zxlib/dockerized_build.mk:85: all] Error 2
```

:link: [zboto Link](https://app.clickup.com/t/2g3ux1g)

**Comment by carlosala** [comment]
I don't have cargo installed on my system and I can run `make` perfectly. Can you try to re-clone the repo and run `git submodule update --init` and then `make`?

**Comment by ftheirs** [comment]
Have you followed these steps?
1) Clone repository
2) Initialize submodules (git submodule update --init)
3) make deps (you need to set python3 as default)
4) make

**Comment by jleni** [comment]
This is because to keep things secure we don't launch the container with root credentials. Instead we mount using the userid that is running make.

You probably have a different user id from the standard two that we support

**Comment by jleni** [comment]
by the way, for normal testing purposes, you can use the artifact that CI outputs directly.

In practice, is the very rare that anybody will need to build this apart from Zondax and Ledger. This is why we have GitHub actions to build and release scripts to simplify testing.

**Comment by jleni** [comment]
if you look at the command line here:

```
docker run "-t" "-i" --rm -e SCP_PRIVKEY=ff701d781f43ce106f72dc26a46b6a83e053b5d07bb3d4ceab79c91ca822a66b -e BOLOS_SDK=/project/deps/nanos-secure-sdk -e BOLOS_ENV=/opt/bolos -u 0 -v /root/ledger-parallel:/project -e SUPPORT_SR25519= -e SUBSTRATE_PARSER_FULL=1 -e COIN= -e APP_TESTING= zondax/builder-bolos:latest "make -C /project clean"
```

in particular the part `-u 0`. Your user id is 0. Did you run this as root?

**Comment by mclyk** [comment]
Yes, `cargo` is not necessary when compiling. and after I change a non-root user, `make` works. Thanks very much.

**Comment by mclyk** [comment]
> by the way, for normal testing purposes, you can use the artifact that CI outputs directly.
> 
> In practice, is the very rare that anybody will need to build this apart from Zondax and Ledger. This is why we have GitHub actions to build and release scripts to simplify testing.

How can I test with artifact that CI outputs, when I am running `./installer_nanos_xl.sh load`, an error happens:
```
Generated random root public key : b'04e4a51376aab8a01780881dd3f976cdc66978fa8d89e669a59c44a28a116001f8f8b1ba67695f665f4436780ae52e3c52048e7fd84d59008f43e6de947ba2fbd3'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/ledgerblue/loadApp.py", line 184, in <module>
    dongle = getDongle(args.apdu)
  File "/usr/local/lib/python3.8/dist-packages/ledgerblue/comm.py", line 240, in getDongle
    raise CommException("No dongle found")
ledgerblue.commException.CommException: Exception : No dongle found
```

I want to use emulated device instead of real device, and test sending some transactions to our parachain. if this is possible? Didn't figure out how can I do this according to the doc: https://github.com/Zondax/ledger-parallel/blob/main/docs/build.md#download-and-install

**Comment by carlosala** [comment]
You need to have the `nanos` device connected to the computer and in the main screen (that with all the apps connected). We don't support emulation for test real transactions.

**Comment by mclyk** [comment]
Ok, does `nanox` work?

**Comment by carlosala** [comment]
No, `nanox` doesn't support loading non-official builds of apps. It only supports ones installed using ledger live, and parallel is not present there yet.

**Comment by mclyk** [comment]
Got it, thanks a lot.
